---
title: "Airbnb in Paris"
author: "Boxuan Yi"
date: "28 Febuary 2024"
date-format: "D MMMM YYYY"
format: pdf
---
```{r}
#| message: false
#| echo: false
library(readr)
library(dplyr)
library(arrow)
library(stringr)
library(ggplot2)
library(naniar)
library(janitor)
library(modelsummary)
library(knitr)
```

```{r}
#| message: false
#| echo: false
url <-
  paste0(
    "http://data.insideairbnb.com/france/ile-de-france/",
    "paris/2023-12-12/data/listings.csv.gz"
  )

airbnb_data <-
  read_csv(
    file = url,
    guess_max = 20000
  )

write_csv(airbnb_data, "airbnb_data.csv")
```

```{r}
#| message: false
#| echo: false
airbnb_data_selected <-
  airbnb_data |>
  select(
    host_id,
    host_response_time,
    host_is_superhost,
    host_total_listings_count,
    neighbourhood_cleansed,
    bathrooms,
    bedrooms,
    price,
    number_of_reviews,
    review_scores_rating,
    review_scores_accuracy,
    review_scores_value
  )

write_parquet(
  x = airbnb_data_selected, 
  sink = "2023-12-12-paris-airbnblistings-select_variables.parquet"
   )

rm(airbnb_data)
```

```{r}
#| message: false
#| echo: false
airbnb_data_selected <-
  airbnb_data_selected |>
  mutate(
    price = str_remove_all(price, "[\\$,]"),
    price = as.integer(price)
  )
```

```{r}
#| label: fig-price
#| fig-cap: Distribution of prices of Paris Airbnb rentals in December 2023
#| echo: false
#| warning: false
#| message: false
#| layout-ncol: 2
#| fig-subcap: ["Distribution of price", "Distribution of Prices Using the Log Scale for Prices More Than $1,000"]
airbnb_data_selected |>
  ggplot(aes(x = price)) +
  geom_histogram(binwidth = 10) +
  theme_classic() +
  labs(
    x = "Price per night",
    y = "Number of properties") 

airbnb_data_selected |>
  filter(price > 1000) |>
  ggplot(aes(x = price)) +
  geom_histogram(binwidth = 10) +
  theme_classic() +
  labs(
    x = "Price per night",
    y = "Number of properties"
  ) +
  scale_y_log10()
```

```{r}
#| label: fig-price_distribution
#| fig-cap: Distribution of prices for Airbnb listings in Paris in December 2023
#| echo: false
#| warning: false
#| message: false
#| layout-ncol: 2
#| fig-subcap: ["Prices less than $1,000 suggest some bunching", "Prices between $90 and $210 illustrate the bunching more clearly"]
airbnb_data_selected |>
  filter(price < 1000) |>
  ggplot(aes(x = price)) +
  geom_histogram(binwidth = 10) +
  theme_classic() +
  labs(
    x = "Price per night",
    y = "Number of properties"
  )

airbnb_data_selected |>
  filter(price > 90) |>
  filter(price < 210) |>
  ggplot(aes(x = price)) +
  geom_histogram(binwidth = 1) +
  theme_classic() +
  labs(
    x = "Price per night",
    y = "Number of properties"
  )
```

```{r}
#| include: false
airbnb_data_less_1000 <-
  airbnb_data_selected |>
  filter(price < 1000)
```

```{r}
#| include: false
airbnb_data_no_superhost_nas <-
  airbnb_data_less_1000 |>
  filter(!is.na(host_is_superhost)) |>
  mutate(
    host_is_superhost_binary =
      as.numeric(host_is_superhost)
  )
```

```{r}
#| message: false
#| echo: false
#| warning: false
#| label: fig-score
#| fig-cap: Distribution of review scores rating for Paris Airbnb rentals in December 2023
airbnb_data_no_superhost_nas |>
  ggplot(aes(x = review_scores_rating)) +
  geom_bar() +
  theme_classic() +
  labs(
    x = "Review scores rating",
    y = "Number of properties"
  )
```

```{r}
#| message: false
#| echo: false
#| warning: false
#| label: fig-score_distribution
#| fig-cap: Distribution of review scores for Paris Airbnb rentals in December 2023
airbnb_data_no_superhost_nas |>
  filter(!is.na(review_scores_rating)) |>
  ggplot(aes(x = review_scores_rating)) +
  geom_histogram(binwidth = 1) +
  theme_classic() +
  labs(
    x = "Average review score",
    y = "Number of properties"
  )
```

```{r}
#| include: false
airbnb_data_has_reviews <-
  airbnb_data_no_superhost_nas |>
  filter(!is.na(review_scores_rating))

airbnb_data_has_reviews |>
  count(host_response_time)
```

```{r}
#| include: false
airbnb_data_has_reviews <-
  airbnb_data_has_reviews |>
  mutate(
    host_response_time = if_else(
      host_response_time == "N/A",
      NA_character_,
      host_response_time
    ),
    host_response_time = factor(host_response_time)
  )
```

```{r}
#| message: false
#| echo: false
#| warning: false
#| label: tbl-time
#| tbl-cap: Distribution of Hosts Response Time for Paris Airbnb in December 2023
airbnb_data_has_reviews |>
  count(host_response_time) |> kable()
```

```{r}
#| message: false
#| echo: false
#| warning: false
#| label: fig-score_distribution_NA
#| fig-cap: Distribution of review scores for properties with NA response time, for Paris Airbnb rentals in December 2023
airbnb_data_has_reviews |>
  filter(is.na(host_response_time)) |>
  ggplot(aes(x = review_scores_rating)) +
  geom_histogram(binwidth = 1) +
  theme_classic() +
  labs(
    x = "Average review score",
    y = "Number of properties"
  )
```

```{r}
#| message: false
#| echo: false
#| warning: false
#| label: fig-missing_value
#| fig-cap: Missing values in Paris Airbnb data, by host response time
airbnb_data_has_reviews |>
  ggplot(aes(
    x = host_response_time,
    y = review_scores_accuracy
  )) +
  geom_miss_point() +
  labs(
    x = "Host response time",
    y = "Review score accuracy",
    color = "Is missing?"
  ) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```

```{r}
#| message: false
#| echo: false
#| warning: false
#| label: fig-properties
#| fig-cap: Distribution of the number of properties a host has on Airbnb, for Paris Airbnb rentals in December 2023
airbnb_data_selected <-
  airbnb_data_has_reviews |>
  filter(!is.na(host_response_time))

airbnb_data_selected |>
  ggplot(aes(x = host_total_listings_count)) +
  geom_histogram() +
  scale_x_log10() +
  labs(
    x = "Total number of listings, by host",
    y = "Number of hosts"
  )
```

```{r}
#| include: false
airbnb_data_selected <-
  airbnb_data_selected |>
  add_count(host_id) |>
  filter(n == 1) |>
  select(-n)
```

```{r}
#| message: false
#| echo: false
#| warning: false
#| label: fig-relationship
#| fig-cap: Relationship between price and review and whether a host is a superhost, for Paris Airbnb rentals in December 2023
airbnb_data_selected |>
  filter(number_of_reviews > 1) |>
  ggplot(aes(x = price, y = review_scores_rating, color = host_is_superhost)) +
  geom_point(size = 1, alpha = 0.08) +
  theme_classic() +
  labs(
    x = "Price per night",
    y = "Average review score",
    color = "Superhost"
  ) +
  scale_color_brewer(palette = "Set1")
```

```{r}
#| include: false
airbnb_data_selected |>
  count(host_is_superhost) |>
  mutate(
    proportion = n / sum(n),
    proportion = round(proportion, digits = 2)
  )
```

```{r}
#| include: false
airbnb_data_selected |>
  tabyl(host_response_time, host_is_superhost) |>
  adorn_percentages("col") |>
  adorn_pct_formatting(digits = 0) |>
  adorn_ns() |>
  adorn_title()
```

```{r}
#| include: false
airbnb_data_selected |>
  tabyl(neighbourhood_cleansed) |>
  adorn_pct_formatting() |>
  arrange(-n) |>
  filter(n > 100) |>
  adorn_totals("row")
```

```{r}
#| include: false
logistic_reg_superhost_response_review <-
  glm(
    host_is_superhost ~
      host_response_time +
      review_scores_rating,
    data = airbnb_data_selected,
    family = binomial
  )
```

```{r}
#| message: false
#| echo: false
#| warning: false
#| label: tbl-model
#| tbl-cap: Explaining whether a host is a superhost based on their response time and review scores
modelsummary(logistic_reg_superhost_response_review)
```

```{r}
#| include: false
write_parquet(
  x = airbnb_data_selected, 
  sink = "2023-05-05-london-airbnblistings-analysis_dataset.parquet"
  )
```
